name: Copy Docker Image
run-name: Copy ${{ inputs.source_repo }} to ${{ inputs.destination_repo }}
on: 
  workflow_dispatch:
    inputs:
      source:
        description: '镜像源 (Registry)'     
        required: true
        default: 'docker.io'
      destination:
        description: '目标源 (Registry)'
        required: true
        default: 'crpi-50lzdkyff1s1q5b3.cn-hangzhou.personal.cr.aliyuncs.com'
      source_repo:
        description: '仓库及标签 (格式 repo:tag)'
        required: true
        default: ''
      destination_repo:
        description: '目标仓库及标签 (格式 repo:tag)'
        required: true
        default: 'liuyang_smartx'

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Docker Images
      uses: aliyun/acr-login@v1
      with:
        destination: ${{ github.event.inputs.destination }}
        destination-credential: ${{ secrets.DESTINATION_CREDENTIAL }}
        copy: "${{ github.event.inputs.source_repo }} ${{ github.event.inputs.destination_repo }}"
